In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
#from word2number import w2n

In [16]:
df = pd.read_csv('3_hiring.csv')
df

experiencia  puntajePrueba  puntajeEntrevista  salarioAlcanzado
0          NaN            8.0                  9           5000000
1          NaN            8.0                  6           4500000
2          5.0            6.0                  7           6000000
3          2.0           10.0                 10           6500000
4          7.0            9.0                  6           7000000
5          3.0            7.0                 10           6200000
6         10.0            NaN                  7           7200000
7         11.0            7.0                  8           8000000

In [17]:
m = df.puntajePrueba.median()
df.puntajePrueba = df.puntajePrueba.fillna(m)
df.experiencia = df.experiencia.fillna(0)
#df.experience = df.experience.apply(w2n.word_to_num)
df.head(4)

experiencia  puntajePrueba  puntajeEntrevista  salarioAlcanzado
0          0.0            8.0                  9           5000000
1          0.0            8.0                  6           4500000
2          5.0            6.0                  7           6000000
3          2.0           10.0                 10           6500000

In [20]:
x = df.drop(['salarioAlcanzado'], axis = 'columns')
x

experiencia  puntajePrueba  puntajeEntrevista
0          0.0            8.0                  9
1          0.0            8.0                  6
2          5.0            6.0                  7
3          2.0           10.0                 10
4          7.0            9.0                  6
5          3.0            7.0                 10
6         10.0            8.0                  7
7         11.0            7.0                  8

In [22]:
model = linear_model.LinearRegression()
model.fit(x, df.salarioAlcanzado)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [23]:
m = model.coef_
m

array([281295.48762737, 184570.59679767, 220524.01746725])

In [24]:
c = model.intercept_
c

1773726.346433768

In [25]:
model.predict([[2, 9 , 6]])

array([5320596.79767103])

In [26]:
model.predict([[12, 10, 10]])

array([9200218.34061136])